Add healthCheck model and controller
Sage-Bionetworks/rocc-service pull request #70
Opened 2021-02-09 19:04 UTC by vpchung

2021-02-10 19:30 UTC, tschaffter requested changes

2021-02-10 19:30 UTC, tschaffter commented on server/openapi_server/openapi/openapi.yaml
> +      responses:
The 500 response is missing. https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/commons/paths/healthCheck.yaml

2021-02-17 00:45 UTC, tschaffter commented
> I also moved the unit tests written for the models out of integration/ and into a unit/ folder.

@vpchung While our tests may look like unit tests because we have one test per endpoint, I still consider them as integration test. For example, if we test DELETE Challenge, it's possible in the future that the controller will perform actions other than simply delete the challenge object from the DB. For example DB objects related to the challenge that are no longer needed may also be deleted by calling other controllers' functions, an email notification may be sent to the challenge manager, etc. Therefore testing and thus calling DELETE Challenge is not testing a single unit of the server but test how well DELETE Challenge integrates into the codebase. A unit test would be the testing of a single class, for example testing a Model class.

2021-02-17 01:44 UTC, vpchung commented
>A unit test would be the testing of a single class, for example testing a Model class.

Agreed, and that's exactly what I did :) The tests for the endpoints remain in `/integration`; I only moved the tests for the models into `/unit`.

2021-02-17 02:12 UTC, vpchung commented
@tschaffter I'm not sure if a `404 Not Found` status code is needed for healthCheck?  Since we are not querying for a specific element within the database, I didn't think we would encounter this error and so, have removed it.

Unless there are some plans down the line where we will query a heathCheck on a specific model perhaps?

2021-02-17 02:33 UTC, tschaffter commented
> I'm not sure if a 404 Not Found status code is needed for healthCheck? Since we are not querying for a specific element within the database, I didn't think we would encounter this error and so, have removed it.

I agree with you.

2021-02-17 02:33 UTC, tschaffter approved these changes
This PR looks great to me!

2021-02-17 02:33 UTC, merged